### Obtener todos los proyectos (GET)
GET http://localhost:5000/api/projects

###

### Crear un nuevo proyecto (POST)
POST http://localhost:5000/api/projects
Content-Type: application/json

{
    "name": "Mi primer proyecto real",
    "description": "Este proyecto ya se está guardando en MongoDB"
}